### ISSUE TITLE
Site comes up blank for me?

### ISSUE THREAD

**Issue by ACPK** [mikamai/angular-rails-example#2]

**Comment by geoom** [comment]
It probably shows you an $location error with a lastest angular version ... maybe you have this issue #3 and it can be solved by change [this line](https://github.com/mikamai/angular-rails-example/blob/master/app/assets/javascripts/angular-rails-example.js.coffee#L18) by:

    $locationProvider.html5Mode
        enabled: true,
        requireBase: false

**Comment by nicolaracco** [comment]
It should work after the fix made for issue #3
