### ISSUE TITLE
$location in HTML5 mode requires a <base> tag to be present!

### ISSUE THREAD

**Issue by geoom** [mikamai/angular-rails-example#3]
you need to specify the base URL for the application with a <base href=""> tag or configure $locationProvider to not require a base tag by passing a definition object with requireBase:false to $locationProvider.html5Mode(),more details [here](https://docs.angularjs.org/error/$location/nobase).

**Comment by nicolaracco** [comment]
Don't know why, but cannot reproduce this. Anyway, I added `<base href="/" />` in the head section of the layout.
Can you confirm the problem is fixed now ?

**Comment by geoom** [comment]
it does!
